RECUR	START	0
FIRST	LDA		THREE
TEST1	CLEAR	X
		CLEAR	A
		LDT		FOUR
TEST2	LDCH	FIVE
		STCH	BUFFER,X
TEST3	LDCH	SIX
		STCH	BUFFER,X
TEST4	CLEAR	X
		CLEAR	A
		LDT		SEVEN
TEST5	CLEAR	X
		CLEAR	A
		LDT		EIGHT
THREE	WORD	3
FOUR	WORD	4
FIVE	WORD	5
SIX		WORD	6
SEVEN	WORD	7
EIGHT	WORD	8
LENGTH	RESW	1
BUFFER	RESB	4096
		END		FIRST