COPY	START	0
.
. This is a macro definition
.
RDBUFF	MACRO	&INDEV,&BUFADR,&RECLTH
		CLEAR	X
		CLEAR	A
		CLEAR	S
		+LDT	#4096
$LOOP	TD		=X'&INDEV'
		JEQ		$LOOP
		RD		=X'&INDEV'
		COMPR	A,S
		JEQ		$EXIT
		STCH	&BUFADR,X
		TIXR	T
		JLT		$LOOP
$EXIT	STX		&RECLTH
		MEND
WRBUFF	MACRO	&OUTDEV,&BUFADR,&RECLTH
		CLEAR	X
		LDT		&RECLTH
		LDCH	&BUFADR,X
$LOOP	TD		=X'&OUTDEV'
		JEQ		$LOOP
		WD		=X'&OUTDEV'
		TIXR	T
		JLT		$LOOP
		MEND
FIRST	STL		RETADR
CLOOP	RDBUFF	F1,BUFFER,LENGTH
		LDA		LENGTH
		COMP	#0
		JEQ		ENDFIL
		WRBUFF	05,BUFFER,LENGTH
		J		CLOOP
ENDFIL	WRBUFF	05,EOF,THREE
		J		@RETADR
EOF		BYTE	C'EOF'
THREE	WORD	3
RETADR	RESW	1
LENGTH	RESW	1
BUFFER	RESB	4096
		END		FIRST